title: it's krankdud
author: Charlie Schuy
exclude:
    - README.md

theme: jekyll-whiteglass
remote_theme: yous/whiteglass
plugins:
    - jekyll-archives
    - jekyll-paginate
    - jekyll-sitemap

permalink: /:year/:month/:day/:title/
paginate_path: /posts/:num/
paginate: 5

markdown: kramdown

jekyll-archive:
    enabled:
        - categories
        - tags
    layout: category_archives
    permalinks:
        category: /categories/:name/
        tag: /tags/:name/
